/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jeffplaisance_mmap_NativeMMapUtils */

#ifndef _Included_com_jeffplaisance_mmap_NativeMMapUtils
#define _Included_com_jeffplaisance_mmap_NativeMMapUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jeffplaisance_mmap_NativeMMapUtils_MAP_FAILED
#define com_jeffplaisance_mmap_NativeMMapUtils_MAP_FAILED -1LL
#undef com_jeffplaisance_mmap_NativeMMapUtils_EACCES
#define com_jeffplaisance_mmap_NativeMMapUtils_EACCES 1L
#undef com_jeffplaisance_mmap_NativeMMapUtils_EAGAIN
#define com_jeffplaisance_mmap_NativeMMapUtils_EAGAIN 2L
#undef com_jeffplaisance_mmap_NativeMMapUtils_EBADF
#define com_jeffplaisance_mmap_NativeMMapUtils_EBADF 3L
#undef com_jeffplaisance_mmap_NativeMMapUtils_EINVAL
#define com_jeffplaisance_mmap_NativeMMapUtils_EINVAL 4L
#undef com_jeffplaisance_mmap_NativeMMapUtils_ENFILE
#define com_jeffplaisance_mmap_NativeMMapUtils_ENFILE 5L
#undef com_jeffplaisance_mmap_NativeMMapUtils_ENODEV
#define com_jeffplaisance_mmap_NativeMMapUtils_ENODEV 6L
#undef com_jeffplaisance_mmap_NativeMMapUtils_ENOMEM
#define com_jeffplaisance_mmap_NativeMMapUtils_ENOMEM 7L
#undef com_jeffplaisance_mmap_NativeMMapUtils_EPERM
#define com_jeffplaisance_mmap_NativeMMapUtils_EPERM 8L
#undef com_jeffplaisance_mmap_NativeMMapUtils_ETXTBSY
#define com_jeffplaisance_mmap_NativeMMapUtils_ETXTBSY 9L
#undef com_jeffplaisance_mmap_NativeMMapUtils_EOVERFLOW
#define com_jeffplaisance_mmap_NativeMMapUtils_EOVERFLOW 10L
/*
 * Class:     com_jeffplaisance_mmap_NativeMMapUtils
 * Method:    mmap0
 * Signature: (JJIIIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_jeffplaisance_mmap_NativeMMapUtils_mmap0
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jlong);

/*
 * Class:     com_jeffplaisance_mmap_NativeMMapUtils
 * Method:    munmap0
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_jeffplaisance_mmap_NativeMMapUtils_munmap0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_jeffplaisance_mmap_NativeMMapUtils
 * Method:    errno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jeffplaisance_mmap_NativeMMapUtils_errno
  (JNIEnv *, jclass);

/*
 * Class:     com_jeffplaisance_mmap_NativeMMapUtils
 * Method:    getDirectBufferAddress
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_com_jeffplaisance_mmap_NativeMMapUtils_getDirectBufferAddress
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
